fixes re-declare issue
```
ErrorException: Cannot declare class Illuminate\Routing\Controller, because the name is already in use
/var/www/html/vendor/rebing/graphql-laravel/src/GraphQLLumenServiceProvider.php:24
/var/www/html/vendor/laravel/lumen-framework/src/Application.php:193
/var/www/html/app/Providers/AppServiceProvider.php:35
```

Additionally, from never-merged commit e854d83d8e9552307b0cbe6044bebee3a431dc5a:
> It is rather simple really.
>  The default testcase in lumen does an app refresh before each test in the setUp method, which does a bootstrap.
>  This means in the same process all classes are being re autoloaded, which is not a problem since it is done with require_once. But the GraphQL does not fall under that since is being re executed and not required.
>
>  So there is an unmet requirement of the register function, it needs to be process idempotent.

Thanks to @ulrichdahl for the additional research!